//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPatient
    {
        public int PatientID { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string JMBG { get; set; }
        public string HealthNumber { get; set; }
        public string Username { get; set; }
        public string Pasword { get; set; }
        public Nullable<int> DoctorID { get; set; }
        public int AbsenceID { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string Reason { get; set; }
        public string Company { get; set; }
        public bool Urgent { get; set; }
        public bool Responsed { get; set; }
    }
}
